# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-08 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.CharField(max_length=80, verbose_name='文件上传时间')),
                ('callday', models.CharField(max_length=30, verbose_name='通话时间(精确到天)')),
                ('calltime', models.CharField(max_length=30, verbose_name='通话时间(精确到秒)')),
                ('calllong', models.IntegerField(verbose_name='通话时长(精确到秒)')),
                ('daytime', models.CharField(max_length=30, verbose_name='通话时段')),
                ('calltype', models.CharField(max_length=30, verbose_name='主被叫')),
                ('landtype', models.CharField(max_length=30, verbose_name='本地异地')),
                ('phonetype', models.CharField(max_length=30, verbose_name='座机手机')),
                ('callphone', models.CharField(max_length=30, verbose_name='电话号码')),
                ('otherarea', models.CharField(max_length=40, verbose_name='对方归属地')),
                ('homearea', models.CharField(max_length=40, verbose_name='本机归属地')),
                ('month', models.CharField(max_length=20, verbose_name='通话时间(精确到月)')),
                ('phoneproperty', models.CharField(max_length=20, verbose_name='号码性质')),
            ],
        ),
        migrations.CreateModel(
            name='File_table',
            fields=[
                ('f_time', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='文件上传时间')),
                ('f_name', models.CharField(max_length=40, verbose_name='文件名')),
                ('call_table', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data_model.Call_table')),
            ],
        ),
        migrations.CreateModel(
            name='Otherarea_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.CharField(max_length=80, verbose_name='文件上传时间')),
                ('name', models.CharField(max_length=30, verbose_name='归属地')),
            ],
        ),
        migrations.AddField(
            model_name='file_table',
            name='otherarea_table',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data_model.Otherarea_table'),
        ),
    ]
